### ISSUE TITLE
clash for windows 0.10.3 引入 rule-providers 后报错

### ISSUE THREAD

**Issue by asdfj2381k** [DivineEngine/Profiles#1]
rule-providers:
  ChinaIP:
    type: http
    behavior: ipcidr
    path: ./RuleSet/Extra/ChinaIP.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/ChinaIP.yaml
    interval: 86400

我在原本可用的配置文件上，仅仅加入这8行。

保存后提示（由于提示窗显示不全，我用ctrl+c复制出来了）：

`[Window Title]
Clash for Windows

[Main Instruction]
Could not switch to this profile!

[Content]
initial rule provider ChinaIP error: Get "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/ChinaIP.yaml": read tcp4 192.168.0.112:6790->151.101.228.133:443: wsarecv: An existing connection was forcibly closed by the remote host.

[Edit in Text Mode] [确定]`

**Comment by asdfj2381k** [comment]
切换配置文件时，这个弹窗没有0.1秒就弹出来了，看起来并不像是因为网络原因而下载失败。

**Comment by ConnersHua** [comment]
DNS 配置部分贴一下？

**Comment by asdfj2381k** [comment]
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - 119.29.29.29
    - 114.114.114.114
    - 223.5.5.5

**Comment by ConnersHua** [comment]
建议尝试禁用 DNS 配置（`enable: true`）或整块直接注释看看，我今天也遇到过两个这样的情况，但和你不同，是使用了 `redir-host` 模式配置了 `fallback` 部分但并不能访问到造成的，他们在注释掉 `fallback` 部分或禁用 DNS 配置后得以解决

**Comment by asdfj2381k** [comment]
![image](https://user-images.githubusercontent.com/56584082/85141426-541a0600-b279-11ea-9e57-3034c595ff5b.png)

DNS模块直接注释掉后，再加入

rule-providers:
ChinaIP:
type: http
behavior: ipcidr
path: ./RuleSet/Extra/ChinaIP.yaml
url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/ChinaIP.yaml
interval: 86400

然后加入
- RULE-SET,ChinaIP,DIRECT
再注释掉
 - GEOIP,CN,DIRECT


保存，没报错了。

但是。。  翻不了墙了（国内网站能上去）。 没任何错误提示。

打开Clash的Connections页，没任何记录。 （即便是国内的访问记录也没显示出来）

**Comment by ConnersHua** [comment]
Profiles 选中默认的 `config.yaml` 后再选到你的配置文件看看有没有报错，还有 Logs 看看有没有报错

**Comment by asdfj2381k** [comment]
```
time="2020-06-19T22:32:33+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-06-19T22:32:33+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-06-19T22:32:33+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2020-06-19T22:32:33+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
time="2020-06-19T22:32:33+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7893"
time="2020-06-19T22:32:33+08:00" level=info msg="Start initial compatible provider MyProxy"
time="2020-06-19T22:32:33+08:00" level=info msg="Start initial rule provider ChinaIP"
time="2020-06-19T22:32:33+08:00" level=info msg="Start initial compatible provider MyProxy"
time="2020-06-19T22:32:33+08:00" level=info msg="Start initial rule provider ChinaIP"
```

**Comment by asdfj2381k** [comment]
问题估计是出在
`time="2020-06-19T22:32:33+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"`
上面。

但是不知道怎么修改了..

**Comment by ConnersHua** [comment]
进入配置文件夹，会有个 RuleSet 文件夹，看一下 ChinaIP.yaml 是否下载成功

**Comment by asdfj2381k** [comment]
![image](https://user-images.githubusercontent.com/56584082/85145356-056f6a80-b27f-11ea-972f-e3904ed3d73c.png)


下载成功了。

**Comment by asdfj2381k** [comment]
。。要不咱们还是直接来吧，估计你也累了 - -..

![image](https://user-images.githubusercontent.com/56584082/85145764-a8c07f80-b27f-11ea-8be3-30996f6adaa1.png)
抹去了两处，其余都没改动。

我的配置文件很短，只有53行。 

[1592572942574.txt](https://github.com/DivineEngine/Profiles/files/4805223/1592572942574.txt)
后缀txt→yml

**Comment by asdfj2381k** [comment]
![image](https://user-images.githubusercontent.com/56584082/85146583-503db200-b280-11ea-8799-9871790e98d0.png)

**Comment by ConnersHua** [comment]
等等……你就只配了 Telegram？那你浏览器能打开 telegram.org 吗

**Comment by asdfj2381k** [comment]
为了方便你看文件，我把一部分规则删掉了。

**Comment by ConnersHua** [comment]
我现在没有电脑，看着好像没有问题，我明天看看吧，是浏览器也打不开外网也没有日志吗？

**Comment by asdfj2381k** [comment]
Connections选项卡里面没任何日志。   能打开国内的网，但是打不开外网。

好的，晚安。

**Comment by asdfj2381k** [comment]
我在虚拟机里面，新安装了一个windows， 用那个配置文件，加入
`- DOMAIN-SUFFIX,githubusercontent.com,MyProxy`  还是不行。

录了屏。。

[bandicam 2020-06-20 10-52-33-905.txt](https://github.com/DivineEngine/Profiles/files/4807272/bandicam.2020-06-20.10-52-33-905.txt)
把txt→mp4

**Comment by ConnersHua** [comment]
Logs 有东西吗

**Comment by asdfj2381k** [comment]
```
time="2020-06-20T10:38:44+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-06-20T10:38:45+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-06-20T10:38:45+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7890"
time="2020-06-20T10:39:09+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-06-20T10:40:47+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-06-20T10:41:01+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-06-20T10:42:09+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-06-20T10:42:28+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-06-20T10:45:01+08:00" level=info msg="Start initial compatible provider MyProxy"
time="2020-06-20T10:45:01+08:00" level=info msg="Start initial rule provider ChinaIP"
time="2020-06-20T10:45:02+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-06-20T10:45:03+08:00" level=info msg="Start initial compatible provider MyProxy"
time="2020-06-20T10:45:03+08:00" level=info msg="Start initial rule provider ChinaIP"
time="2020-06-20T10:48:11+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-06-20T10:48:13+08:00" level=info msg="Start initial compatible provider MyProxy"
time="2020-06-20T10:48:13+08:00" level=info msg="Start initial rule provider ChinaIP"
time="2020-06-20T10:49:16+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-06-20T10:49:27+08:00" level=info msg="Start initial compatible provider MyProxy"
time="2020-06-20T10:49:27+08:00" level=info msg="Start initial rule provider ChinaIP"
time="2020-06-20T10:49:28+08:00" level=info msg="Start initial compatible provider MyProxy"
time="2020-06-20T10:49:28+08:00" level=info msg="Start initial rule provider ChinaIP"
time="2020-06-20T10:50:40+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-06-20T10:50:44+08:00" level=info msg="Start initial compatible provider MyProxy"
time="2020-06-20T10:50:44+08:00" level=info msg="Start initial rule provider ChinaIP"
time="2020-06-20T10:50:59+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-06-20T10:51:00+08:00" level=info msg="Start initial compatible provider MyProxy"
time="2020-06-20T10:51:00+08:00" level=info msg="Start initial rule provider ChinaIP"
time="2020-06-20T10:52:37+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-06-20T10:52:39+08:00" level=info msg="Start initial compatible provider MyProxy"
time="2020-06-20T10:52:39+08:00" level=info msg="Start initial rule provider ChinaIP"
time="2020-06-20T10:56:01+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-06-20T10:56:01+08:00" level=info msg="Start initial compatible provider MyProxy"
time="2020-06-20T10:56:01+08:00" level=info msg="Start initial rule provider ChinaIP"

```

**Comment by ConnersHua** [comment]
```
  ChinaIP:
    type: file
    behavior: ipcidr
    path: ./RuleSet/Extra/ChinaIP.yaml
```

手动下载用本地引用吧...

我问了 F 大了之前，他说是这 provider 没下成功导致，但我看你截图又是下好了的

**Comment by asdfj2381k** [comment]
![image](https://user-images.githubusercontent.com/56584082/85190065-29ff2d00-b2e7-11ea-8b55-0f45597273f5.png)

修改后还是不行。。 

算了，我累了。。估计是clash自身的问题，等F大修一下BUG吧。

**Comment by asdfj2381k** [comment]
F大如果看到这里，说句话吧，我开teamviewer给你玩一下。  （24小时等你 么么哒）

**Comment by asdfj2381k** [comment]
![image](https://user-images.githubusercontent.com/56584082/85190321-df32e480-b2e9-11ea-8e23-fdfb25516420.png)


删掉RuleSet文件夹后，无法重新自动下载。 头疼。

**Comment by ConnersHua** [comment]
DNS 用 DoH 看看吧：`https://doh.rixcloud.dev/dns-query`

**Comment by asdfj2381k** [comment]
![image](https://user-images.githubusercontent.com/56584082/85361640-1229e200-b54f-11ea-9a1b-436c144b06bd.png)

成功了，问题解决了。

**Comment by ConnersHua** [comment]
🎉

**Comment by asdfj2381k** [comment]
tmd

不是DoH的问题。

终于排查出来了。

![image](https://user-images.githubusercontent.com/56584082/85362826-14417000-b552-11ea-99a3-ee8d6adaee56.png)

**Comment by ConnersHua** [comment]
找我反馈的也有这个模式下失败的

**Comment by kqlemwtze** [comment]
也遇到了同样的问题，“type”放弃使用“http”了，改用“file”，可以正常使用了。

~~~yaml
  Unbreak:
    type: file
    behavior: classical
    path: ./RuleSet/Unbreak.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/RuleSet/Unbreak.yaml
    interval: 86400
~~~

**Comment by asdfj2381k** [comment]
0.10.4修正了这个问题，现在用fake-ip也可以正常下载rule providers了。

**Comment by domoxiaojun** [comment]
> 。。要不咱们还是直接来吧，估计你也累了 - -..
> 
> ![image](https://user-images.githubusercontent.com/56584082/85145764-a8c07f80-b27f-11ea-8be3-30996f6adaa1.png)
> 抹去了两处，其余都没改动。
> 
> 我的配置文件很短，只有53行。
> 
> [1592572942574.txt](https://github.com/DivineEngine/Profiles/files/4805223/1592572942574.txt)
> 后缀txt→yml

这个是国内IP直连国外全部走代理吗

**Comment by asdfj2381k** [comment]
恩，大概是这样的效果。

**Comment by domoxiaojun** [comment]
> 恩，大概是这样的效果。

简洁实用,谢谢分享~

**Comment by yks1sky** [comment]
0.14.3版本又遇到了这个问题
