### ISSUE TITLE
CLASH引入规则错误

### ISSUE THREAD

**Issue by Yixuling** [DivineEngine/Profiles#10]
![image](https://user-images.githubusercontent.com/29663375/87761766-9ddc1900-c844-11ea-9331-83214076b4f7.png)

**Comment by gzgaryli** [comment]
我也存在同一问题，看之前的ISSUE，试了所说的办法都不行。

**Comment by kqlemwtze** [comment]
这似乎是因为“raw.githubusercontent.com”被污染了，或许可以在hosts文件里添加记录“199.232.68.133 raw.githubusercontent.com”尝试一下。

**Comment by ConnersHua** [comment]
`raw.githubusercontent.com` 被污染，尝试在系统的 hosts 指定 IP 到如 151.101.0.133 解决，如果还不行就用 jsDelivr 吧

**Comment by Yixuling** [comment]
嗯，问题解决了。但是出现这样的一个情况
![image](https://user-images.githubusercontent.com/29663375/87765610-9a4b9080-c84a-11ea-9b16-8a24c925e14b.png)
看了之前的ISSUE,好像不行

**Comment by gzgaryli** [comment]
广东的，用这个可解决 199.232.68.133 raw.githubusercontent.com
谢谢各位大佬

**Comment by Yixuling** [comment]
嗯 改了hosts 199.232.68.133 raw.githubusercontent.com 也可以了
谢谢
