### ISSUE TITLE
大家怎么解决divine配置在clash for Android 的下载失败的问题的

### ISSUE THREAD

**Issue by trulynb** [DivineEngine/Profiles#101]
明明网页可以打开   但是一直报错connection refused
![image](https://user-images.githubusercontent.com/17597573/106552773-e219d700-6552-11eb-9992-0728b0d49913.png)

**Comment by xuhuanxxx** [comment]
url前面加个 https://ghproxy.com/ ，像这样 https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml

**Comment by trulynb** [comment]
> url前面加个 https://ghproxy.com/ ，像这样 https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml

牛逼  谢谢
