### ISSUE TITLE
IP- Blockhole误杀

### ISSUE THREAD

**Issue by zsbai** [DivineEngine/Profiles#109]
<img width="775" alt="截屏2021-02-12 下午9 50 20" src="https://user-images.githubusercontent.com/62942942/107776273-5129d380-6d7c-11eb-9145-fd113064d811.png">
突然发现谷歌不能访问，在surge dashboard里发现居然是被ip- blockhole拦截了，以前是可以访问的，配置文件都没有动的情况下出现被拦截的情况
<img width="775" alt="截屏2021-02-12 下午9 53 02" src="https://user-images.githubusercontent.com/62942942/107776554-af56b680-6d7c-11eb-9794-5e609c56f864.png">

**Comment by ConnersHua** [comment]
IP-Blockhole.list 为什么要 REJECT？

**Comment by zsbai** [comment]
> IP-Blockhole.list 为什么要 REJECT？

抱歉是blackhole，blackhole不应该使用reject嘛？

**Comment by ConnersHua** [comment]
这个原意主要是被墙的 IP 段（现在不怎么维护了），一般来说不引入，特别是如果你的 Final 日常使用 PROXY 完全可以不使用的

**Comment by zsbai** [comment]
> 这个原意主要是被墙的 IP 段（现在不怎么维护了），一般来说不引入，特别是如果你的 Final 日常使用 PROXY 完全可以不使用的

😥抱歉我理解错了，感谢

**Comment by ConnersHua** [comment]
没事，新年快乐

**Comment by zsbai** [comment]
> 没事，新年快乐

新年快乐🎉
