### ISSUE TITLE
Streaming.yaml, domain清单中混入了IP-CIDR，会出什么问题？

### ISSUE THREAD

**Issue by OUZYcn** [DivineEngine/Profiles#12]
https://github.com/DivineEngine/Profiles/blob/master/Clash/RuleSet/StreamingMedia/Streaming.yaml

  # > Netflix
  # USER-AGENT,Argo*
  - DOMAIN-SUFFIX,netflix.com
  - DOMAIN-SUFFIX,netflix.net
  - DOMAIN-SUFFIX,nflxext.com
  - DOMAIN-SUFFIX,nflximg.com
  - DOMAIN-SUFFIX,nflximg.net
  - DOMAIN-SUFFIX,nflxso.net
  - DOMAIN-SUFFIX,nflxvideo.net
  - DOMAIN-SUFFIX,netflixdnstest0.com
  - DOMAIN-SUFFIX,netflixdnstest1.com
  - DOMAIN-SUFFIX,netflixdnstest2.com
  - DOMAIN-SUFFIX,netflixdnstest3.com
  - DOMAIN-SUFFIX,netflixdnstest4.com
  - DOMAIN-SUFFIX,netflixdnstest5.com
  - DOMAIN-SUFFIX,netflixdnstest6.com
  - DOMAIN-SUFFIX,netflixdnstest7.com
  - DOMAIN-SUFFIX,netflixdnstest8.com
  - DOMAIN-SUFFIX,netflixdnstest9.com
  - IP-CIDR,23.246.0.0/18,no-resolve
  - IP-CIDR,37.77.184.0/21,no-resolve
  - IP-CIDR,45.57.0.0/17,no-resolve
  - IP-CIDR,64.120.128.0/17,no-resolve
  - IP-CIDR,66.197.128.0/17,no-resolve
  - IP-CIDR,108.175.32.0/20,no-resolve
  - IP-CIDR,192.173.64.0/18,no-resolve
  - IP-CIDR,198.38.96.0/19,no-resolve
  - IP-CIDR,198.45.48.0/20,no-resolve

**Comment by ConnersHua** [comment]
能有什么问题？

**Comment by OUZYcn** [comment]
> 能有什么问题？不知道你要表达什么

例如仅DOMAIN生效，而IP-CIDR不生效。
毕竟按照https://lancellc.gitbook.io/clash/clash-config-file/rule-provider的说明
**behavior**
the type of rules, it can be a `domain `, `ipcidr  `or `classical`.  `domain `means all things in it must be a domains, `ipcidr `means all things in it must be a ip cidrs, `classical `means it is a rules liked rule-provider

**Comment by ConnersHua** [comment]
![ClashXPro.png](https://i.loli.net/2020/07/21/MLNPkXsWHqnlirj.png)

实测当匹配 IP-CIDR 规则时生效

behavior 有三个选项，`doamin`、`ipcidr` 和 `classical`，`doamin` 只能有域名；`ipcidr` 只能有 IP-CIDR；`classical` 为传统格式，三者格式均不同

**Comment by OUZYcn** [comment]
> ![ClashXPro.png](https://camo.githubusercontent.com/b3206dbe47429e7f8ba02539eba4c841e8b1b8dc/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30372f32312f4d4c4e506b58735748716e6c69726a2e706e67)
> 
> 实测当匹配 IP-CIDR 规则时生效
> 
> behavior 有三个选项，`doamin`、`ipcidr` 和 `classical`，`doamin` 只能有域名；`ipcidr` 只能有 IP-CIDR；`classical` 为传统格式，三者格式均不同

感谢答复，我回去查config.yaml看了，里边自动用最普世的`classical`，所以应该是涵盖了`doamin`、`ipcidr` 的约定。

**Comment by ConnersHua** [comment]
> > 实测当匹配 IP-CIDR 规则时生效
> > behavior 有三个选项，`doamin`、`ipcidr` 和 `classical`，`doamin` 只能有域名；`ipcidr` 只能有 IP-CIDR；`classical` 为传统格式，三者格式均不同
> 
> 感谢答复，我回去查config.yaml看了，里边自动用最普世的` behavior: classical`，所以应该是涵盖了`doamin`、`ipcidr` 的约定。
> 但若是 `behavior: doamin` ，那么rule-set.yaml中的`ipcidr`规则就应该不生效了对吧？

格式不对，会报错
