### ISSUE TITLE
微软域名补充

### ISSUE THREAD

**Issue by tsln1998** [DivineEngine/Profiles#124]
当前 Clash 配置文件中包含
```
  - DOMAIN,az416426.vo.msecnd.net
  - DOMAIN,az668014.vo.msecnd.net
```

建议修改为
`DOMAIN-SUFFIX,vo.msecnd.net`

**Comment by tsln1998** [comment]
目前VSCode macOS universal的下载链接为
`https://az764295.vo.msecnd.net/stable/f30a9b73e8ffc278e71575118b6bf568f04587c8/VSCode-darwin-universal.zip`

**Comment by ConnersHua** [comment]
vo.msecnd.net 其他子域未被污染，「MATCH」策略组可选「PROXY」达到你要的效果

**Comment by tsln1998** [comment]
这个域名的子域多用来作为做文件分发

比如 VSCode 那个子域，不少地区网络连接较差，导致下载中断。应该能属于 Global.yaml 的 Network Jitter 范围。
