### ISSUE TITLE
关于Xbox服务的疑问

### ISSUE THREAD

**Issue by tanglueyi** [DivineEngine/Profiles#125]
根据这篇帖子：[《Xbox One 当前国内 CDN 状态分析 149.129.113.81 原理解析 IPv6 通道高速下载方法》](https://bbs.a9vg.com/thread-5478226-1-1.html)，我将我的配置做了如下更改：

在原来的基础上增加了`*.xboxlive.cn`
```
[General]
always-real-ip = msftconnecttest.com, msftncsi.com, *.msftconnecttest.com, *.msftncsi.com, *.srv.nintendo.net, *.stun.playstation.net, xbox.*.microsoft.com, *.xboxlive.com, *.xboxlive.cn
```
通过`Xbox`策略控制`*.xboxlive.com`与`*xboxlive.cn`的分流
```
[rule]
# > Xbox
DOMAIN-SUFFIX,xboxlive.cn,Xbox
RULE-SET,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Extra/Game/Xbox.list,Xbox

```
强制以下域名解析到`23.2.16.32`
```
[host]
# Xbox Download
assets1.xboxlive.com = 23.2.16.32
assets2.xboxlive.com = 23.2.16.32
dlassets.xboxlive.com = 23.2.16.32
assets1.xboxlive.cn = 23.2.16.32
assets2.xboxlive.cn = 23.2.16.32
dlassets.xboxlive.cn = 23.2.16.32
```

下载环境有所改善，我的问题是在`always-real-ip`项中是否有加入`*.xboxlive.cn`的必要？

**Comment by ConnersHua** [comment]
使用 `always-real-ip` 是因为「由于游戏主机会使用 STUN 技术进行 NAT 穿透，需要进行一些额外的配置才能正常工作。」

https://nssurge.zendesk.com/hc/zh-cn/articles/900000208886-Surge-Mac-%E8%B7%AF%E7%94%B1%E6%A8%A1%E5%BC%8F%E7%89%B9%E6%AE%8A%E8%AE%BE%E5%A4%87%E5%85%BC%E5%AE%B9%E8%AF%B4%E6%98%8E

但我个人并没有 Xbox 不能给出肯定答复，另外这只是下载服务个人觉得没有必要加入

**Comment by tanglueyi** [comment]
> 使用 `always-real-ip` 是因为「由于游戏主机会使用 STUN 技术进行 NAT 穿透，需要进行一些额外的配置才能正常工作。」
> 
> https://nssurge.zendesk.com/hc/zh-cn/articles/900000208886-Surge-Mac-%E8%B7%AF%E7%94%B1%E6%A8%A1%E5%BC%8F%E7%89%B9%E6%AE%8A%E8%AE%BE%E5%A4%87%E5%85%BC%E5%AE%B9%E8%AF%B4%E6%98%8E
> 
> 但我个人并没有 Xbox 不能给出肯定答复，另外这只是下载服务个人觉得没有必要加入

好的，另外我`rule`和`host`部分配置合理吗？

**Comment by ConnersHua** [comment]
大体看着没什么问题，就是如果你想要代理按照 `[Host]` 中的设置，需要加上：

```
[General]
use-local-host-item-for-proxy = true
```

**Comment by tanglueyi** [comment]
> 大体看着没什么问题，就是如果你想要代理使用 `[Host]` 部分中定义的 IP 地址（而不是原始域）发送代理请求，需要加上：
> 
> ```
> [General]
> use-local-host-item-for-proxy = true
> ```

感谢答复，use-local-host-item-for-proxy = true这个参数中文叫什么没有见过，我在UI中没找着

**Comment by ConnersHua** [comment]
这个是 Surge Mac 3.5.3 加入的新参数，只在更新日志里提到

**Comment by tanglueyi** [comment]
> 这个是 Surge Mac 3.5.3 加入的新参数，只在更新日志里提到

您不说还真的不知道，感谢

**Comment by ConnersHua** [comment]
不客气哈
