### ISSUE TITLE
在使用苹果HomeKit家庭app的时候，调取摄像机监控画面的时候回出现连接不上的情况

### ISSUE THREAD

**Issue by ininolee** [DivineEngine/Profiles#127]
在使用苹果HomeKit家庭app的时候，调取摄像机监控画面的时候回出现连接不上的情况

**Comment by ConnersHua** [comment]
https://community.nssurge.com/d/144-ios-surge-homekit

>经过我们仔细确认，这是 iOS 自己的一个问题，HomeKit 与摄像头建立连接时，会主动将本机 IP 发送给摄像头端逆向连接。
但是 iOS 并未处理 VPN 开启时的情况，会将 VPN 的内网地址发送给摄像头，导致 RTSP 数据回包无法发回到 iOS 设备上，我们没有能想出该问题的 workaround，只能等待 iOS 解决。
