### ISSUE TITLE
提交两个去广告分流，不会pr

### ISSUE THREAD

**Issue by wrong5210** [DivineEngine/Profiles#129]
#IKOS
host, tracker-download.oss-cn-beijing.aliyuncs.com, reject

#漫画柜
host, ad.sitemaji.com, reject
host, ads.aralego.com, reject

**Comment by ConnersHua** [comment]
感谢反馈，但第一条存在误杀，IKOS 的下载链接是？

**Comment by wrong5210** [comment]
> 感谢反馈，但第一条存在误杀，IKOS 的下载链接是？

https://apps.apple.com/cn/app/ikos/id1310191517

**Comment by ConnersHua** [comment]
已处理
