### ISSUE TITLE
误杀反馈：plbslog.umeng.com

### ISSUE THREAD

**Issue by Chandler-Lu** [DivineEngine/Profiles#131]
## 情况
**iPadOS 软件**使用 Umeng 三方登陆接口（ https://developer.umeng.com/docs/143070/detail/171114 ）的微信登录时，微信中登录二维码不显示。

## 复现
1. **iPadOS** 和风天气 -> 登录 -> 微信登录 -> 跳转至微信，需要手机扫描的登录二维码不显示。

## 原因
初步判断为 plbslog.umeng.com 被误杀

**Comment by ConnersHua** [comment]
已处理，感谢反馈
