### ISSUE TITLE
News.list 响应时间过长，且 Apple news 部分内容无法刷新

### ISSUE THREAD

**Issue by YvesMiao** [DivineEngine/Profiles#134]
![29A8F299-F518-4487-BC50-B29C1E0F0C66](https://user-images.githubusercontent.com/81374628/112497348-7c163700-8dc0-11eb-8d0a-705dae0ae37a.jpeg)
News-events.apple.com 与 c.apple.news 均出现此问题

**Comment by ConnersHua** [comment]
建议更换节点使用
