### ISSUE TITLE
Surge Advertising.sgmodule 会影响今日头条的热榜刷新

### ISSUE THREAD

**Issue by sjy-nankai** [DivineEngine/Profiles#135]
如果开启这个module，今日头条的热榜标签无法刷新内容

**Comment by ben-august** [comment]
排除去广告中的这个规则 p3.pstatp.com

**Comment by ConnersHua** [comment]
未能复现

**Comment by sjy-nankai** [comment]
> 排除去广告中的这个规则 p3.pstatp.com

你好，在神机规则中没有找到你说的这个

**Comment by sjy-nankai** [comment]
> 未能复现

你好，我的圈X和Surge都会因为Advertising.sgmodule和Advertising.conf导致今日头条的“热榜”，“热点”，本地新闻等标签无法刷出列表信息。

具体原因我这里没详细找到，只是把这个相关的模块disable就正常了。

我再找找原因吧

**Comment by ConnersHua** [comment]
可以尝试：（先重开以清掉不相关的请求，其他应用最好划掉后台）使用 Quantumult X，然后刷新「热榜」等相关页面，在「网络活动」查看粉色链接和数据为 0 的请求，以及查看「日志」中有没有 MitM Faild 的日志

**Comment by sjy-nankai** [comment]
> 可以尝试：（先重开以清掉不相关的请求，其他应用最好划掉后台）使用 Quantumult X，然后刷新「热榜」等相关页面，在「网络活动」查看粉色链接和数据为 0 的请求，以及查看「日志」中有没有 MitM Faild 的日志

你好，我尝试了一下，没有MitM Faild的日志，有这个数据为0的请求。 具体请求如下。

另外我用Charles抓包，「热榜」请求的是这个链接

https://api5-normal-c-lq.snssdk.com/api/news/feed/v88/?caid1=f504afc818b1c52c618f1b4227aaeb17&app_version=8.1.8&vid=05FFB15F-0D36-44A1-ADD2-57860F63EEC7&carrier_region=CN&idfv=05FFB15F-0D36-44A1-ADD2-57860F63EEC7&caid2=&ab_client=a1,f2,f7,e1&idfa=00000000-0000-0000-0000-000000000000&image=1&list_count=0&count=20&tt_from=unknown&category=news_hotspot&last_refresh_sub_entrance_interval=16014738&user_city=%E5%A4%A7%E8%BF%9E&refer=1&ad_ui_style=%7B%22van_package%22%3A130000050%2C%22is_crowd_generalization_style%22%3A2%7D&refresh_reason=0&concern_id=&st_time=3401&session_refresh_idx=1&strict=0&LBS_status=authroize&rerank=0&detail=1&client_extra_params=%7B%22recommend_enable%22%3A1%2C%22lynx_version_json%22%3A%22%7B%5C%22ugc_common_lynx%5C%22%3A79722%2C%5C%22tt_lynx_hotboard%5C%22%3A76903%2C%5C%22ugc_personal_page%5C%22%3A77400%2C%5C%22new_local_forum_cell%5C%22%3A76200%2C%5C%22toutiao_lynx_main%5C%22%3A17%2C%5C%22ugc_lynx_wenda%5C%22%3A74615%2C%5C%22lynx_city_channel%5C%22%3A76500%2C%5C%22learning_lynx_card%5C%22%3A78200%2C%5C%22amos_basic_lynx%5C%22%3A81700%2C%5C%22ugc_lynx_hotboard%5C%22%3A75548%2C%5C%22tt_search_lynx_cell%5C%22%3A81300%2C%5C%22ugc_lynx_native_hotboard_card%5C%22%3A74201%2C%5C%22ugc_lynx_survey%5C%22%3A76400%2C%5C%22attach_post_card%5C%22%3A76803%2C%5C%22toutiao_lynx_card%5C%22%3A77300%2C%5C%22new_local_stick_cell%5C%22%3A76300%2C%5C%22wallet_portal_lynx%5C%22%3A74001%2C%5C%22learning_lynx_profile%5C%22%3A77700%2C%5C%22tt_video_recommend_cell%5C%22%3A79400%7D%22%2C%22last_ad_position%22%3A-1%2C%22playparam%22%3A%22codec_type%3A1%2Cenable_dash%3A1%2Cunwatermark%3A1%22%2C%22sort_offset%22%3A%220%22%7D&min_behot_time=0&loc_mode=1&cp=620f671783FE2q1&

**Comment by ConnersHua** [comment]
Quantumult X 可以点进请求链接拉至底部可以看到「状态」

**Comment by sjy-nankai** [comment]
> Quantumult X 可以点进请求链接拉至底部可以看到「状态」

策略走向：DIRECT
状态：已关闭

**Comment by sjy-nankai** [comment]
> Quantumult X 可以点进请求链接拉至底部可以看到「状态」

你好，通过你告诉我的这个方法，我找到原因了。

是我都添加了tiktok的rewrite，区域重写成国外了，应该是这个原因

**Comment by ConnersHua** [comment]
额，没事
