### ISSUE TITLE
rewrite规则导致京东比价脚本失效

### ISSUE THREAD

**Issue by m3u8playlist** [DivineEngine/Profiles#140]
把这2条规则删了就正常了
^https?:\/\/api\.m\.jd.com\/client\.action\?functionId=start url reject
^https?:\/\/api\.m\.jd.com\/client\.action\?functionId=queryMaterialAdverts url reject

**Comment by ConnersHua** [comment]
https://github.com/yichahucha/surge/blob/master/README.md

作者的使用说明已经有提到：
```
# 不生效或失效的检查一下配置有没有这两条复写，删除试试
# ^https?:\/\/api\.m\.jd.com\/client\.action\?functionId=start - reject
# ^https?:\/\/api\.m\.jd.com\/client\.action\?functionId=(start|queryMaterialAdverts) - reject
```

可以用资源解析器使用 `out` 参数禁用
