### ISSUE TITLE
中国移动app加载非常慢，几乎无法正常打开

### ISSUE THREAD

**Issue by wangbo-ops** [DivineEngine/Profiles#141]
![IMG_0181](https://user-images.githubusercontent.com/71998512/114833657-66fe5800-9e02-11eb-9850-a6ee3df5eaf0.PNG)

**Comment by ConnersHua** [comment]
请求记录里查看 10086.cn 域名的相关请求情况，最好上个图

**Comment by wangbo-ops** [comment]
![IMG_0182](https://user-images.githubusercontent.com/71998512/114840431-63220400-9e09-11eb-8d05-3a3a8fd966ad.JPEG)

**Comment by ConnersHua** [comment]
去 DNS 面板看 10086.cn 是哪个 DNS 服务器的结果

**Comment by wangbo-ops** [comment]
![IMG_7111BE8128B9-1](https://user-images.githubusercontent.com/71998512/114842087-1808f080-9e0b-11eb-9bb5-0edc06ca4c6b.jpeg)

**Comment by wangbo-ops** [comment]
dns配置
![IMG_81CC614151C6-1](https://user-images.githubusercontent.com/71998512/114842349-57374180-9e0b-11eb-8b29-d99667b30ad8.jpeg)

**Comment by ConnersHua** [comment]
无语，用运营商的 DNS 都出问题...

0 KB 的请求点进去拉到最低，「状态」那栏有什么错误么

**Comment by wangbo-ops** [comment]
点了很多都看了一下，要么是“已关闭”，要么是“Attempt to connect to host timed out”

**Comment by ConnersHua** [comment]
sdc1.10086.cn 在我这也是超时，其他正常。话说不开 Quantumult X 正常么，我怀疑是移动自己都问题

**Comment by wangbo-ops** [comment]
正常的，现在用的时候就只能先关掉quanx

**Comment by ConnersHua** [comment]
尝试 `[general]` 下的 `dns_exclusion_list=` 加一个 `*.10086.cn` 看看

**Comment by wangbo-ops** [comment]
试了一下，还是不行。
![IMG_FBEAA78A7829-1](https://user-images.githubusercontent.com/71998512/114847789-ab90f000-9e10-11eb-83d8-94dd955b2d90.jpeg)

**Comment by ConnersHua** [comment]
我现在想不到是为什么，先暂时这么用吧

**Comment by wangbo-ops** [comment]
好的，大佬后续有更新我在来看看👌

**Comment by wangbo-ops** [comment]
换surge以后正常，推测可能是quanx的问题。
