### ISSUE TITLE
FaceTime视频通话在PROXY下无法接通

### ISSUE THREAD

**Issue by wangbo-ops** [DivineEngine/Profiles#145]
无论是拨出还是对方拨过来，点击接通会显示“正在连接”，然后连接失败。
测试了一下，将QuanX关掉或者Final设为DIRECT即可正常接通。

**Comment by ConnersHua** [comment]
可以使用
```
[general]
# 默认为 reject
fallback_udp_policy=direct
```

从 1.0.19+ 版本开始 Quantumult X 因为
> 节点不开启 UDP 支持回退到直连的行为与逻辑不符。会产生 UDP 流量与 TCP 流量的源地址不同的结果（在对应应用的服务提供商看来）。

会对策略为代理的 UDP 请求，但所用的节点并不支持 UDP 转发（如 VMess、Trojan）或支持但配置中未声名 `udp-relay=true` 的采取 REJECT 策略

更多关于 Quantumult X 的 UDP 相关信息可查看：https://t.me/QuanXNews/167
