### ISSUE TITLE
xp.apple.com走全球的

### ISSUE THREAD

**Issue by ziking** [DivineEngine/Profiles#147]
itunes.apple.com
testflight.apple.com
能不能再苹果apple.list里面增加

**Comment by ConnersHua** [comment]
https://github.com/DivineEngine/Profiles/blob/a0b3a3248fa0f13999ea2c9c68bb457715d12e4d/Surge/Ruleset/Extra/Apple/Apple.list#L4

**Comment by ConnersHua** [comment]
`DOMAIN,itunes.apple.com` 不会影响 App Store 下载使其走代理，DOMAIN-SUFFIX 才会

`DOMAIN,testflight.apple.com` 已经被污染

**Comment by ziking** [comment]
非常感谢回复，我试一下。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Conners ***@***.***&gt;; 
发送时间: 2021年4月22日(星期四) 上午8:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DivineEngine/Profiles] xp.apple.com走全球的 (#147)





 
DOMAIN,itunes.apple.com 不会影响 App Store 下载使其走代理，DOMAIN-SUFFIX 才会
 
DOMAIN,testflight.apple.com 已经被污染
 
&mdash;

**Comment by AndyCoke-Max** [comment]
请问 xp.apple.com是苹果什么服务，为什么走全球？可不可以直连？
