### ISSUE TITLE
[BUG]rewitte 导致比价脚本失效

### ISSUE THREAD

**Issue by srk24** [DivineEngine/Profiles#148]
^https?:\/\/api\.m\.jd.com\/client\.action\?functionId=start url reject
^https?:\/\/api\.m\.jd.com\/client\.action\?functionId=queryMaterialAdverts url reject

这两条会导致比价脚本失效

**Comment by ConnersHua** [comment]
https://github.com/DivineEngine/Profiles/issues/140#issuecomment-820160371
