### ISSUE TITLE
雪球APP IOS下规则失效

### ISSUE THREAD

**Issue by iawes** [DivineEngine/Profiles#164]
最新的开屏广告可能是这样的
但我添加到本地之后，好像还是不能去广告
恳请大神帮忙下，平时用的最多的就是雪球了
谢谢

https://api.xueqiu.com/ads/display/show.json?ads_id=1000008401&uid=3297902216&_=1620801651211&_s=232fed&_t=0185E471-7979-4D93-887A-DE644ABDF095.3297902216.1620801643668.1620801643722

**Comment by ConnersHua** [comment]
你好，你应该是写了类似这样的 Rewrite 并配置了 hostname：
```
^https://api.xueqiu.com/ads/display/show.json?ads - reject
```
还出现的情况可以尝试删除 App 重装

**Comment by iawes** [comment]
> 
> 
> 你好，你应该是写了类似这样的 Rewrite 并配置了 hostname：
> 
> ```
> ^https://api.xueqiu.com/ads/display/show.json?ads - reject
> ```
> 
> 还出现的情况可以尝试删除 App 重装

我是这样写的，而且重装了APP，不过好像还是不行

**Comment by ConnersHua** [comment]
应该解决了

**Comment by iawes** [comment]
嗯嗯，好像是可以了> 应该解决了
