### ISSUE TITLE
关于雪球app社区不能刷新

### ISSUE THREAD

**Issue by sky003-Max** [DivineEngine/Profiles#174]
雪球的相关hostname不能mitm，否则会导致社区内容不能刷新
相关
> Xueqiu - api.xueqiu.com,promo.xueqiu.com,182.92.251.113,101.201.175.228

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by ConnersHua** [comment]
具体哪个位置的内容不能刷新？

**Comment by sky003-Max** [comment]
雪球app，点进去的推荐就看不了

**Comment by ConnersHua** [comment]
无法复现

**Comment by sky003-Max** [comment]
![C86A660B-FD95-4775-B9FC-9E09A50C5FD8](https://user-images.githubusercontent.com/56504601/124084423-8b70e480-da81-11eb-88ff-b7397a8645a4.png)
