### ISSUE TITLE
大佬，想要Gcash的list，会增加吗？

### ISSUE THREAD

**Issue by aff2018** [DivineEngine/Profiles#175]
大佬，想要Gcash的list，会增加吗？
这家用非菲律宾IP登陆会风控。

**Comment by ConnersHua** [comment]
看了下，比较难，我没有菲律宾的号码

**Comment by aff2018** [comment]
https://www.yinsiduanxin.com/philippines-phone-number.html
这里的手机号肯定失败。但可以进行注册接码使用，会显示：让工单联系Gcash

**Comment by ConnersHua** [comment]
你可以尝试，如果不行就自己抓吧
```
USER-AGENT,GCash*
DOMAIN-SUFFIX,gcash.com
DOMAIN-SUFFIX,mynt.xyz
```
