### ISSUE TITLE
希望China增加有道的域名

### ISSUE THREAD

**Issue by randyho** [DivineEngine/Profiles#178]
最近在上网易云课堂，发现走了代理，经常打不开，希望China这个文件里面NetEasy处增加youdao.com

**Comment by stanleyblue** [comment]
你自己改一下不就得了

Sent from Nine<http://www.9folders.com/>

________________________________
发件人： Randy ***@***.***>
发送时间： 2021年7月14日星期三 22:46
收件人： DivineEngine/Profiles
抄送： Subscribed
主题： [DivineEngine/Profiles] 希望China增加有道的域名 (#178)


最近在上网易云课堂，发现走了代理，经常打不开，希望China这个文件里面NetEasy处增加youdao.com

―

**Comment by ConnersHua** [comment]
感谢反馈，已处理
