### ISSUE TITLE
zeep app被误拦截了 

### ISSUE THREAD

**Issue by lyl12321** [DivineEngine/Profiles#179]
非常不好意思的打扰一下，因为我是华米手表的用户，但zeep（华米app）的 api-mifit-cn2.huami.com:443 接口被误拦截了，导致我没法再使用app的所有功能，我是圈x用户，使用的是https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Rewrite/Block/Advertising.conf 这个规则

**Comment by ConnersHua** [comment]
感谢反馈，已处理
