### ISSUE TITLE
增加 TingFM 反广告的规则

### ISSUE THREAD

**Issue by xixaxoqiqaqo** [DivineEngine/Profiles#180]
![0A6C2FBC-2CA2-43CE-8A22-79280DB6DA55](https://user-images.githubusercontent.com/78405720/126314650-441d999b-3afd-405d-9d93-8eea0a4180c8.jpeg)

- 个别域名怎么不经过 QuantumultX 处理, 不知道 ip

**Comment by ConnersHua** [comment]
建议用其他客户端

**Comment by xixaxoqiqaqo** [comment]
> 建议用其他客户端

- 谢谢，换个思路提取电台地址保持到备忘录
