### ISSUE TITLE
iOS腾讯欢乐麻将全集无法闪退

### ISSUE THREAD

**Issue by wangbo-ops** [DivineEngine/Profiles#184]
检查最近请求应该是广告屏蔽造成。

03:01:42.796833 Sub-rule matched: DOMAIN-SUFFIX iadsdk.apple.com
03:01:42.796877 Rule matched: RULE-SET Advertising.list
03:01:42.799036 Disconnect with reason: Reject by rule

03:01:42.822923 Sub-rule matched: DOMAIN-KEYWORD adservice
03:01:42.822961 Rule matched: RULE-SET Advertising.list
03:01:42.823855 Disconnect with reason: Reject by rule

**Comment by ConnersHua** [comment]
更新新版后好像不闪退了

**Comment by wangbo-ops** [comment]
更新后确实不闪退了。> 更新新版后好像不闪退了
