### ISSUE TITLE
YouTube 去广告的重写规则失效

### ISSUE THREAD

**Issue by lxp0gb** [DivineEngine/Profiles#185]
最近一个月，YouTube 去广告的重写规则失效。

**Comment by Skyxim** [comment]
同样发现，存在无限302的看情况
![IMG_0075](https://user-images.githubusercontent.com/70276018/128467436-e131e388-4c03-4b6c-907f-d9b8724ebaa5.PNG)
![image](https://user-images.githubusercontent.com/70276018/128467521-e1e1f665-6047-40aa-b8cd-dc183679137c.png)

**Comment by lxp0gb** [comment]
surge的YouTube去广告重写规则有更新，qx的还没更新，可用参考surge的规则转成qx格式即可。

**Comment by ConnersHua** [comment]
已处理
