### ISSUE TITLE
这条会影响nga第一次加载帖子加载不出或较慢

### ISSUE THREAD

**Issue by srk24** [DivineEngine/Profiles#19]
广告里面的这条 DOMAIN-SUFFIX,tagtic.cn。reject之后，nga无论在手机（Safari）还是pc（Chrome），打开nga的帖子时，第一次总是刷新不出，需要再刷新一遍，页面才会加载，这条删除之后恢复正常。

**Comment by srk24** [comment]
- DOMAIN,bdtj.tagtic.cn,DIRECT
建议在unbreak增加一条这个

**Comment by ConnersHua** [comment]
感谢反馈，已处理。
