### ISSUE TITLE
设置 doh-server 后打不开路由器域名管理地址

### ISSUE THREAD

**Issue by xixaxoqiqaqo** [DivineEngine/Profiles#190]
- tplogin.cn

**Comment by ConnersHua** [comment]
以 Surge 为例：
https://github.com/DivineEngine/Profiles/blob/4aa5727d7d0d06793dc5afcfafe881d66ac22f50/Surge/Outbound.conf#L169

**Comment by xixaxoqiqaqo** [comment]
> 以 Surge 为例：
> 
> https://github.com/DivineEngine/Profiles/blob/4aa5727d7d0d06793dc5afcfafe881d66ac22f50/Surge/Outbound.conf#L169

- 感谢，我试过server=/tplogin.cn/255.5.5.5 😊

**Comment by ConnersHua** [comment]
如果是 Quantumult X 应该是 `server=/tplogin.cn/system`，造成问题的原因就是公共 DNS 没有解析结果，你这时候还给个公共 DNS 没有意义
