### ISSUE TITLE
直接下来之后就报错

### ISSUE THREAD

**Issue by yfnok** [DivineEngine/Profiles#197]
首先我改动添加了我的节点，在Android手机上不能使用，来来回回很多次不能用，放弃。
在Windows电脑上调试配置文件，来来回回很多次不能使用，放弃
我不改了，直接用下载下来的出国版本，好吧， 还是不能使用，提示一样的错误
错误如图所示，有没有人遇到过
https://i.loli.net/2021/09/05/ET7uctQaGifqwm1.png

**Comment by ConnersHua** [comment]
你需要阅读「说明」：https://github.com/DivineEngine/Profiles/blob/master/Clash/README.md
