### ISSUE TITLE
知乎无法正常联网

### ISSUE THREAD

**Issue by wangbo-ops** [DivineEngine/Profiles#198]
MIUI 12.5
知乎 7.28.0
clash for android 2.4.9. premium
捕捉日志好像也看不到什么异常

![Screenshot_2021-09-11-18-44-04-264_com.zhihu.android.jpg](https://user-images.githubusercontent.com/71998512/132945181-02e6e5ea-a228-4d7c-a6e6-ff9c51ff61b6.jpg)

**Comment by wangbo-ops** [comment]
相关日志似乎就只有这两条

[TCP] dial DIRECT (match RuleSet/China) to appcloud2.in.zhihu.com error: couldn't find ip

[TCP] dial DIRECT (match GeoIP/CN) to 2402:4e00:1200:ed00:0:9089:6dac:96b6 error: ip version error

**Comment by ConnersHua** [comment]
第一条看着像是 DNS 配置的问题，第二条 `ipv6: false` 改成 true 了么

**Comment by wangbo-ops** [comment]
> 第一条看着像是 DNS 配置的问题，第二条 `ipv6: false` 改成 true 了么

修改以后还是不行
![Screenshot_2021-09-11-22-45-49-287_com.rhmsoft.edit.jpg](https://user-images.githubusercontent.com/71998512/132951686-b3463265-76e9-4cda-8d71-1a5e45c4924f.jpg)
![Screenshot_2021-09-11-22-46-01-212_com.rhmsoft.edit.jpg](https://user-images.githubusercontent.com/71998512/132951693-df10f4f5-cffb-4829-bc21-075c29aabaa6.jpg)

**Comment by wangbo-ops** [comment]
clash for android 升级到2.4.12.premium后解决此问题。
