### ISSUE TITLE
Apple TV app解锁AppleTV+入口

### ISSUE THREAD

**Issue by xuhuanxxx** [DivineEngine/Profiles#203]
之前 iOS、tvOS、macOS 甚至安卓端的 Apple TV app 都能直接解锁 AppleTV+ 入口，昨天 iOS、tvOS 端的 AppleTV+ 的入口突然被没收了。尝试代理日志里多出来的域名 `uts-api.itunes.apple.com`，发现可以解决问题，建议添加一下吧，感谢。

**Comment by ConnersHua** [comment]
感谢反馈，已处理。
