### ISSUE TITLE
抖音去广告水印脚本失效（16.1.0旧版本APP下）

### ISSUE THREAD

**Issue by chaizia** [DivineEngine/Profiles#210]
`^https?:\/\/api.*\.amemv\.com\/aweme\/v\d\/(?!(comment|namek|series|shop)) url request-header ^GET \/aweme\/v\d\/(.+\r\n)Host:.+(\r\n) request-header GET /aweme/v1/$1Host: aweme.snssdk.com$2
^https?:\/\/api.*\.amemv\.com\/aweme\/v[12]\/((|follow\/|nearby\/)feed|aweme\/post|hot\/search\/video\/list|mix\/aweme|aweme\/detail)\/\? url script-response-body https://raw.githubusercontent.com/Choler/Surge/master/Script/douyin.js
`

应该还是这个写法不对，圈X无法加载脚本，只要登陆了抖音，马上就不再加载脚本了。

loon下有效，附上loon配置：
`[URL Rewrite]
# 抖音 去广告&水印
# 需配合脚本使用
^https?:\/\/.+?\.amemv\.com\/aweme\/v\d\/feed\/ https://aweme.snssdk.com/aweme/v1/feed/ header
^https?:\/\/.+?\.amemv\.com\/aweme\/v\d\/aweme\/post\/ https://aweme.snssdk.com/aweme/v1/aweme/post/ header
^https?:\/\/.+?\.amemv\.com\/aweme\/v\d\/follow\/feed\/ https://aweme.snssdk.com/aweme/v1/follow/feed/ header
^https?:\/\/.+?\.amemv\.com\/aweme\/v\d\/nearby\/feed\/ https://aweme.snssdk.com/aweme/v1/nearby/feed/ header
^https?:\/\/.+?\.amemv\.com\/aweme\/v\d\/search\/item\/ https://aweme.snssdk.com/aweme/v1/search/item/ header
^https?:\/\/.+?\.amemv\.com\/aweme\/v\d\/general\/search\/single\/ https://aweme.snssdk.com/aweme/v1/general/search/single/ header
^https?:\/\/.+?\.amemv\.com\/aweme\/v\d\/hot/search\/video\/list\/ https://aweme.snssdk.com/aweme/v1/hot/search/video/list/ header

[Script]
http-response ^https?:\/\/aweme\.snssdk\.com\/aweme\/v1\/(feed|aweme\/post|follow\/feed|nearby\/feed|search\/item|general\/search\/single|hot\/search\/video\/list)\/ requires-body=1,max-size=-1,script-path=https://Choler.github.io/Surge/Script/douyin.js, requires-body=true, timeout=10, tag=抖音去水印

[MITM]
hostname = *.amemv.com`

**Comment by ConnersHua** [comment]
已进行调整，但不是每次都可用，有时请求里没有 feed 路径

**Comment by chaizia** [comment]
> 已进行调整，但不是每次都可用，有时请求里没有 feed 路径

我实测发现不知道是不是quanx优先级的问题，必须让*. amemv.com走代理，才能每次都顺利加载脚本，如果直连则基本不会加载脚本没法去广告和水印。

**Comment by spirytuslove** [comment]
具体要怎么去水印啊 下载视频每次都有水印啊。。

**Comment by ConnersHua** [comment]
> > 已进行调整，但不是每次都可用，有时请求里没有 feed 路径
> 
> 我实测发现不知道是不是quanx优先级的问题，必须在指定下让*. amemv.com走代理，才能每次都顺利加载脚本，否则基本上不会加载脚本没法去广告和水印。

我测试将 dig.bdurl.net 代理后也可以，那这条就关闭吧

**Comment by chaizia** [comment]
> > > 已进行调整，但不是每次都可用，有时请求里没有 feed 路径
> > 
> > 
> > 我实测发现不知道是不是quanx优先级的问题，必须在指定下让*. amemv.com走代理，才能每次都顺利加载脚本，否则基本上不会加载脚本没法去广告和水印。
> 
> 我测试将 dig.bdurl.net 代理后也可以，那这条就关闭吧

多谢大佬，那我就直接把dig.bdurl.net加进代理了

**Comment by ConnersHua** [comment]
疑似将 `dig.bdurl.net` 加入到 `dns_exclusion_list` 也可以，而且还不用走代理

**Comment by chaizia** [comment]
> 疑似将 `dig.bdurl.net` 加入到 `dns_exclusion_list` 也可以，而且还不用走代理

很费解，那这是什么原理呢？
