### ISSUE TITLE
能否单独收集一下 Apple Music TV？

### ISSUE THREAD

**Issue by shawnchiu96** [DivineEngine/Profiles#212]
Apple Music TV 的广播限定地区，不支持的地区会提示 This performance is not available.

目前已知代理 tv.applemusic.com:443 在 US，[Music.list](https://github.com/DivineEngine/Profiles/blob/master/Surge/Ruleset/Extra/Apple/Music.list) 和 [TV.list](https://github.com/DivineEngine/Profiles/blob/master/Surge/Ruleset/Extra/Apple/TV.list) 均直连即可正常访问 Apple Music TV。不知道还有没有其他域名。

**Comment by ConnersHua** [comment]
可以截图说明下具体位置吗，我不使用 Apple Music，不太清楚你说的 Apple Music TV 具体位置

**Comment by shawnchiu96** [comment]
目前至少在 Music app 和 TV app 均有入口，具体如下：

1. 音乐 app - 浏览 - [向下滑一点] - 「广播不间断」栏目下的 Apple Music TV。
![image](https://user-images.githubusercontent.com/8230879/141468529-05e37f13-75b2-4343-8194-09edca55dcc2.jpeg)

2. 视频 app - 立即观看 - [向下滑一点] - Apple Music TV。
![image](https://user-images.githubusercontent.com/8230879/141468587-3c20408f-6d1c-4936-80e6-163262684caa.jpeg)

说明：Apple Music 里面的其他广播节目不受影响，只有 Apple Music TV 比较特殊。

感谢～

**Comment by ConnersHua** [comment]
你抓的 `tv.applemusic.com` 正好，看分享按钮 Apple 把它归类成「电台」，所以我将它和另一条「广播」里的放在一起
