### ISSUE TITLE
油管去广告后直接从头播放

### ISSUE THREAD

**Issue by OPQZZY** [DivineEngine/Profiles#213]
油管去广告加载后，只要一起效就从头播放视频。

**Comment by Skyxim** [comment]
(^https?:\/\/[\w-]+\.googlevideo\.com\/(?!(videoplayback).+)&ip=(.+)(&.+) $1&ip=202.133.207.46$3 header
可以尝试将原本的重定向换成这个。IP选择随便一个送中的IP，我暂时测试能做到送中节点的去广告效果，不过加载速度和以前一样

**Comment by ben-august** [comment]
+1

**Comment by yinpengfeisky** [comment]
我也是，已经🈶️一周多这种情况了

**Comment by hkix** [comment]
同样遇到了这个情况，每次播放到有广告的时间点，都会从头再开始播放。可能是更新了最新App版本的原因

**Comment by waysup** [comment]
quanx 情况属实

**Comment by ConnersHua** [comment]
先降级到 16.43.2 看吧，[降级方法 >](https://divineengine.net/how-to-download-older-versions-of-ios-apps/)
