### ISSUE TITLE
添加Apple Podcasts

### ISSUE THREAD

**Issue by zeyugao** [DivineEngine/Profiles#214]
Apple Podcasts的相当一部分的如果使用直连会导致404，但是把整个Apple划入代理不太合适

已经观测到的域名是 `podcasts.apple.com`，在 Podscast应用里面也会显示有 `bookkeeper.itunes.apple.com`、 `play.itunes.apple.com` 以及 `xp.apple.com` 的访问，添加了 `podcasts.apple.com` 以及 `itunes.apple.com` 作为 host-suffix 之后仍然是无法访问 Apple Podcasts 里面的一些内容

在添加了上面的两个 host-suffix 就可以访问 https://podnews.net/podcast/i5ram/links 了，但是通过点击 Listen On Apple Podcasts 跳转到应用是显示无法连接

不太清楚是否还与账户区域有关。

**Comment by ConnersHua** [comment]
这是大概 19 年 6 月开始的国区屏蔽自主托管的 podcast，并不能通过简单的代理解决，建议换区收听

**Comment by shen-chao** [comment]
美区Apple Podcasts [浏览] 标签页也无法访问了,应该是最近苹果主动屏蔽的,podcasts.apple.com域名配置走代理就可以正常访问了,建议在Apple分类下新建Podcasts规则文件

**Comment by ConnersHua** [comment]
感谢反馈，已处理
