### ISSUE TITLE
可否支持流媒体的具体策略？

### ISSUE THREAD

**Issue by Kawauso-Jyou** [DivineEngine/Profiles#215]
现在的策略只是简单的将流媒体分为了国内国外，但国外不同的流媒体需要的节点也不同，比如Disney与Netflix使用不同的节点才能使得资源最多。

**Comment by ConnersHua** [comment]
`StreamingMedia` 目录下的独立分流文件就是做这个的，新建个策略组，然后 Ruleset 的策略就是策略组名称就行

**Comment by Kawauso-Jyou** [comment]
> `StreamingMedia` 目录下的独立分流文件就是做这个的，新建个策略组，然后 Ruleset 的策略就是策略组名称就行

![06C169C8-270E-464E-A5A2-139CAC42551D](https://user-images.githubusercontent.com/92703641/142120228-dc4d70aa-bf24-44e4-96fc-a428aa395559.png)
![0E8B3162-E524-4673-B187-FFAC76B17392](https://user-images.githubusercontent.com/92703641/142120278-653d23cb-d8b8-4b93-be9c-ebd0eb4ddda7.png)

在没有找到「使用排序要求」的说明呢？

**Comment by ConnersHua** [comment]
独立流媒体分流文件至少放在 `Streaming.list` 之前就行

**Comment by Kawauso-Jyou** [comment]
> 独立流媒体分流文件至少放在 `Streaming.list` 之前就行

好的，谢谢🙏
