### ISSUE TITLE
quanx是不可以使用AdvertisingPlus.list吗

### ISSUE THREAD

**Issue by z1mpleee** [DivineEngine/Profiles#217]
AdvertisingPlus.list，enable=True的话会报Resource parser result with invalid Line .1phads.com

**Comment by ConnersHua** [comment]
https://github.com/DivineEngine/Profiles/blob/de1f6726da0fc1fa45863ff85975f95d7ac3cd6b/Quantumult/Outbound.conf#L162

加 `#type=domain-set`

**Comment by z1mpleee** [comment]
> https://github.com/DivineEngine/Profiles/blob/de1f6726da0fc1fa45863ff85975f95d7ac3cd6b/Quantumult/Outbound.conf#L162
> 
> 加 `#type=domain-set`

可以了，谢谢
