### ISSUE TITLE
关于surge module，可否在代码内解除对macOS的限制，方便macOS M1（及后续）机型安装及更新

### ISSUE THREAD

**Issue by sanziliu** [DivineEngine/Profiles#218]
你好，

请教过surge服务团队，提示macOS surge不能安装module，只要在编写module时代码解除机型限制即可。

之所以提议，是现在使用M1 pro机型可以安装部分iOS/iPadOS版本的app，比如微博iOS官方客户端（其他app类似）。因为不好直接在线安装module，只好自己编写了微博去广告script，mac的adguard去不了app内广告。profile是icloud同步的（懒。。。），这样iOS/iPadOS就冗余了这部分代码（功能重复），虽然也不影响使用。

多谢

**Comment by sanziliu** [comment]
把Block Advertising Plus内的“#!system=ios”删除，建立了本地module，macOS surge就可以用了。如果能把github里代码也处理一下，那么surge for iOS/macOS就都可以在线更新了。thanks

**Comment by dcty** [comment]
> 把Block Advertising Plus内的“#!system=ios”删除，建立了本地module，macOS surge就可以用了。如果能把github里代码也处理一下，那么surge for iOS/macOS就都可以在线更新了。thanks

如果是 Mac 的话，那么其实自己动手一下更简单。

**Comment by sanziliu** [comment]
我本地自建了，是不麻烦。之所以提议作者是否可以把系统限定代码行删除，是现在M1芯片的mac可以安装（部分）app，有些module多系统共用效果非常好，比如常用的微博去广告。

From: dcty ***@***.***>
Date: Friday, December 3, 2021 at 9:03 AM
To: DivineEngine/Profiles ***@***.***>
Cc: Feng ***@***.***>, Author ***@***.***>
Subject: Re: [DivineEngine/Profiles] 关于surge module，可否在代码内解除对macOS的限制，方便macOS M1（及后续）机型安装及更新 (Issue #218)

把Block Advertising Plus内的“#!system=ios”删除，建立了本地module，macOS surge就可以用了。如果能把github里代码也处理一下，那么surge for iOS/macOS就都可以在线更新了。thanks

如果是 Mac 的话，那么其实自己动手一下更简单。

―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDivineEngine%2FProfiles%2Fissues%2F218%23issuecomment-985126902&data=04%7C01%7C%7Cb859d6b42677401da6e408d9b5f8a807%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637740901839622910%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PuD5kego0T9IntlwGRXyvA5wTN9uR7wMBI%2B1oTLDzmI%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIRZIPSO7HG3KDSCNMOHNQDUPAJMNANCNFSM5JAUV4OQ&data=04%7C01%7C%7Cb859d6b42677401da6e408d9b5f8a807%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637740901839622910%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9TuekKLS%2B1yvOKz1%2FTPy2log6FKYlsStc%2F2qok%2BAdhU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cb859d6b42677401da6e408d9b5f8a807%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637740901839632869%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7nWJiR7CgXrmUMXmBrSgVaMMdU4S428u9fCL5wLBbLU%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cb859d6b42677401da6e408d9b5f8a807%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637740901839632869%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MY6hYf40Ml1f3WMcSLchUIIlWJ2T9rg2eMvuL5%2B85Bs%3D&reserved=0>.

**Comment by ConnersHua** [comment]
已处理
