### ISSUE TITLE
youtube去视频广告能跳过广告，但是遇到广告后，会自动从头开始播放视频。

### ISSUE THREAD

**Issue by eastlhu** [DivineEngine/Profiles#219]
机型：iPhone 11
APP：Quantumult X
过滤规则：https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Rewrite/Block/YouTubeAds.conf

**Comment by yiiyahui** [comment]
+1

**Comment by xtfllbl** [comment]
+1，这个没法解决下吗？

**Comment by kissyouhunter** [comment]
+1
更新到ios15.2开始出现这个问题了

**Comment by sadan9** [comment]
+1 
另外应该不是ios的问题，应该有youtube应用的问题

**Comment by ConnersHua** [comment]
先降级到 16.43.2 看吧，[降级方法 >](https://divineengine.net/how-to-download-older-versions-of-ios-apps/)

**Comment by mtgq** [comment]
同样的问题

**Comment by jackexin** [comment]
iOS15.2也是这样，总是从头看……

**Comment by xtfllbl** [comment]
> 先降级到 16.43.2 看吧，[降级方法 >](https://divineengine.net/how-to-download-older-versions-of-ios-apps/)

降级使用后仍然发生相同情况，并未解决问题。
