### ISSUE TITLE
新增 Apple/Books 分流规则

### ISSUE THREAD

**Issue by shawnchiu96** [DivineEngine/Profiles#229]
可能包括但不限于以下：

1. buy.itunes.apple.com
2. books.itunes.apple.com
3. bookkeeper.itunes.apple.com
4. amp-api.books.apple.com
5. se.itunes.apple.com
6. books-analytics-events.apple.com

以上在使用 Apple Books 图书商店时均有触发请求，不过在「试读」时如果不将「1.」走代理会提示「在您的国家不提供试读」，其他直连目前来看不影响使用。希望在 Extra/Apple 目录下为 Books 增加分流规则。

**Comment by ConnersHua** [comment]
感谢反馈，已处理。
