### ISSUE TITLE
微信小程序广告误杀

### ISSUE THREAD

**Issue by kid-oh** [DivineEngine/Profiles#236]
Advertising.list列表中Tencent里的DOMAIN,wxsnsdy.wxs.qq.com和DOMAIN,wxsnsdythumb.wxs.qq.com这两条规则会导致小程序广告无法加载，会影响一些通过观看广告来领取奖励的小程序，比如一些游戏

**Comment by ConnersHua** [comment]
感谢反馈，已处理。
