### ISSUE TITLE
agora.io 走直连会导致某些语音服务无法连接

### ISSUE THREAD

**Issue by tanglueyi** [DivineEngine/Profiles#244]
`agora.io`位于`china.list`则导致设计软件[Figma](figma.com)中语音服务无法连接：

![image](https://user-images.githubusercontent.com/3315564/151116491-066a77a8-914d-4c56-a5a6-d65f2770dbe2.png)

手动分流到代理后可以正常连接：
`DOMAIN-SUFFIX,agora.io,Proxy`

![image](https://user-images.githubusercontent.com/3315564/151116958-bb93897a-df6c-46fa-b34e-affe4961c906.png)

![image](https://user-images.githubusercontent.com/3315564/151117265-ac80af18-e6cf-4a2d-bb00-56cef78fd313.png)

**Comment by ConnersHua** [comment]
感谢反馈，已处理。
