### ISSUE TITLE
芒果 TV 视频无法正常加载播放

### ISSUE THREAD

**Issue by shawnchiu96** [DivineEngine/Profiles#246]
StreamingMedia/Streaming.list（走代理） 中的 api.mgtv.com 会导致芒果 TV 客户端中的视频播放异常，在 iPhone 上的表现为：视频加载缓慢，视频信息、评论、选集等无法加载，通过手机号 + 密码登录请求超时；在 iPad 上的表现为：视频无法加载，视频信息、评论、选集等无法加载。

建议优先保证芒果 TV 国内版正常使用，使用 Extra 或其他方式完善需要使用芒果 TV 海外版的用户。

**Comment by ConnersHua** [comment]
感谢反馈，已处理。
