### ISSUE TITLE
Apple News规则不见了 Surge板块

### ISSUE THREAD

**Issue by james411c** [DivineEngine/Profiles#256]
如题

**Comment by ConnersHua** [comment]
可使用 https://github.com/VirgilClyne/iRingo 模块解锁，所需代理规则已包含在 Global.list 中

**Comment by james411c** [comment]
> 可使用 https://github.com/VirgilClyne/iRingo 模块解锁，所需代理规则已包含在 Global.list 中

感谢回复，可否透露一下集成到Global.list中的原因是什么？以及以前有一条需要的把地图变成Tom tom的好像没有看到在里面。

**Comment by ConnersHua** [comment]
使用该项目不需要代理导致地图数据变成 TOMTOM 了

**Comment by james411c** [comment]
> 使用该项目不需要代理导致地图数据变成 TOMTOM 了

搞定了，谢谢。 Issue closed.
