### ISSUE TITLE
rfdjlrj.gnway.org 走direct访问超时，走代理可以正常访问

### ISSUE THREAD

**Issue by wangbo-ops** [DivineEngine/Profiles#261]
这个域名是工作用的一个app登录时请求的。QX无论是全局直连还是规则分流，都是超时无法访问。全局代理模式可以正常访问，关掉QX也可以正常访问。
请大佬帮忙查一下原因。

**Comment by ConnersHua** [comment]
可以尝试加入到 `[general]` 下的 `dns_exclusion_list` 里看看能不能解决问题
