### ISSUE TITLE
unbreak中包含dl.google.com导致无法下载与更新adb

### ISSUE THREAD

**Issue by Mosney** [DivineEngine/Profiles#266]
页面为：https://developer.android.com/studio/releases/platform-tools
下载链接为：https://dl.google.com/android/repository/platform-tools-latest-windows.zip

**Comment by ConnersHua** [comment]
请确保 `dl.google.com` 由国内 DNS 解析，复测解析至 220.181.174.225、58.254.149.161 均正常

**Comment by Mosney** [comment]
看了一下DNS log确实都解析到了172.217.0.0/16上去。我得考虑一下是在DNS上预分流一下还是在clash加一个un-unbreak🤔
