### ISSUE TITLE
GEOIP位于China.list，是否可以将配置里的GEOIP移除

### ISSUE THREAD

**Issue by tanglueyi** [DivineEngine/Profiles#269]
LAN的位置是否也需要调整

**Comment by ConnersHua** [comment]
LAN 的位置为什么需要调整？

**Comment by tanglueyi** [comment]
> LAN 的位置为什么需要调整？

因为一般情况下LAN是位于GEOIP之上的所以有此一问

**Comment by ConnersHua** [comment]
加了 `no-resolve` 不用担心触发 DNS 解析的问题，该条对于 Surge 用户来说相当于多余在 China.list 强调了 IP 请求直连，除非你对于 GEOIP,CN 有特殊策略，否则可忽略该条规则

**Comment by tanglueyi** [comment]
> 加了 `no-resolve` 不用担心触发 DNS 解析的问题，该条对于 Surge 用户来说相当于多余在 China.list 强调了 IP 请求直连，除非你对于 GEOIP,CN 有特殊策略，否则可忽略该条规则

所以就是说保持原来的状态（就像您的sample config）不变也没啥问题是吗？

**Comment by ConnersHua** [comment]
对的

**Comment by tanglueyi** [comment]
> 对的

谢谢🙏
