### ISSUE TITLE
英雄联盟手游在游戏开始之前会连接不上

### ISSUE THREAD

**Issue by lkj2619** [DivineEngine/Profiles#272]

**Comment by lkj2619** [comment]
极地大乱斗模式

**Comment by ConnersHua** [comment]
如果是 Quantumult X 尝试开启 `icmp_auto_reply=true`

**Comment by lkj2619** [comment]
好的，谢谢。

**Comment by ConnersHua** [comment]
可以了吗

**Comment by lkj2619** [comment]
还是不行

**Comment by lkj2619** [comment]
重启过qx了

**Comment by lkj2619** [comment]
![image](https://user-images.githubusercontent.com/12730151/159173510-d1ff8b93-7caa-44d3-85ae-3ee54272a657.png)

**Comment by ConnersHua** [comment]
你玩的英雄联盟是国服吗？

**Comment by lkj2619** [comment]
是的，更新规则之前可以的，之前四个策略的时候没问题

**Comment by ConnersHua** [comment]
那看看在 `udp_whitelist` 之前加上英文分号注释掉能不能解决

**Comment by lkj2619** [comment]
会不会是因为我没开启mitm？

**Comment by lkj2619** [comment]
好滴我试试

**Comment by lkj2619** [comment]
![image](https://user-images.githubusercontent.com/12730151/159175136-aa9c8d9f-b3b6-4bb4-a16d-dcff61d7bd34.jpeg)

**Comment by ConnersHua** [comment]
在湖蓝色那个 DNS 面板搜一下这个域名然后截个图

**Comment by lkj2619** [comment]
![image](https://user-images.githubusercontent.com/12730151/159175345-a33e299a-5706-4040-a8f5-9fe1b2298483.jpeg)

**Comment by ConnersHua** [comment]
直接截图「网络活动」右侧的「DNS」

**Comment by lkj2619** [comment]
![image](https://user-images.githubusercontent.com/12730151/159175819-18c98b8c-41fb-46a1-80c5-9b8f5234c3b6.png)

**Comment by lkj2619** [comment]
![image](https://user-images.githubusercontent.com/12730151/159175875-5bf153fe-7e22-42c6-8855-cad224068a80.png)

**Comment by ConnersHua** [comment]
你的 GeoIP 库有问题，这几个 IP 是移动的但是没在库里，在「其他设置」里「GeoLite2」的「来源」填写使用「 https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb 」并开启「自动更新」应该就没问题了

**Comment by lkj2619** [comment]
已经好了，谢谢作者，辛苦了❤️
