### ISSUE TITLE
百度云icon误杀反馈

### ISSUE THREAD

**Issue by Chandler-Lu** [DivineEngine/Profiles#32]
https://github.com/DivineEngine/Profiles/blob/5ceea422f07868e2718a0aad07f152640e9769c4/Quantumult/Rewrite/Advertising.conf#L82

与百度云的某些icon有关，如果不是有意reject的话，希望可以放行，谢谢

![IMG_4335](https://user-images.githubusercontent.com/18322610/92112187-ff217100-ee1f-11ea-9cd3-7ee31687f34d.PNG)

![IMG_4336](https://user-images.githubusercontent.com/18322610/92112195-021c6180-ee20-11ea-80d1-64944f9f8255.PNG)

**Comment by ConnersHua** [comment]
已处理，感谢反馈。
