### ISSUE TITLE
safebrowsing.googleapis.com一直走代理路线

### ISSUE THREAD

**Issue by NSLogName** [DivineEngine/Profiles#33]
你好，感谢提供规则，最近发现safebrowsing.googleapis.com这个一直会消耗代理的流量，可否考虑将此设置为走Direct？

**Comment by ConnersHua** [comment]
可以自行添加规则 `DOMAIN,safebrowsing.googleapis.com,DIRECT`，此条有悖 Privacy.list 无法加入到 Unbreak.list
