### ISSUE TITLE
请问下有没有手游的规则

### ISSUE THREAD

**Issue by CGuoL** [DivineEngine/Profiles#39]
rt，想找吃鸡国际服的规则，但是没有找到。

**Comment by ConnersHua** [comment]
如果你用的 Surge 可以加一条规则在 `GEOIP,CN` 规则之后：

```
PROTOCOL,UDP,游戏节点
```

建一个游戏节点策略组，在玩游戏的时候将该策略组开启至代理，平常建议直连
