### ISSUE TITLE
Quantumult X更新后，有一些脚本显示需要更新

### ISSUE THREAD

**Issue by geheng1234** [DivineEngine/Profiles#4]
![image](https://user-images.githubusercontent.com/28821891/85420345-a9ba1f80-b5a5-11ea-8f63-09f2996fd96b.png)

不知道如何进行更新

**Comment by ConnersHua** [comment]
点击右侧圆形图标选择「更新脚本」

（等你购买时间达到 90 天后会看到一键更新按钮）

**Comment by geheng1234** [comment]
好的谢谢，原来就是按旁边的按钮，麻烦了

**Comment by ConnersHua** [comment]
10.12 疑似不用等 90 天就有一键更新按钮了，你可以更新了看看
