### ISSUE TITLE
从app store更新app界面访问外区app详情显示无法连接

### ISSUE THREAD

**Issue by tanglueyi** [DivineEngine/Profiles#5]
我是国区账号，更新app时会有美区app会一起更新，但是点击美区app进详情时会无法连接（国区app没问题），apple.list定义为direct。
![image](https://user-images.githubusercontent.com/3315564/85434210-471e4f00-b5b8-11ea-93f9-ea01647bbc69.png)

**Comment by ConnersHua** [comment]
正常，你登陆非国区账号一样看不到不在外区上架的应用

**Comment by tanglueyi** [comment]
是这样的吗，抱歉我之前确实没注意这点，打扰了
