### ISSUE TITLE
whatsapp issue

### ISSUE THREAD

**Issue by iam3ddy** [DivineEngine/Profiles#51]
Using the ruleset for Clash.
Unable to make voice calls.

**Comment by 6rube** [comment]
Same for me.

**Comment by ConnersHua** [comment]
Voice calls need to be made over UDP (some areas can be made without a proxy), please ensure that PROXY is selected for the policy MATCH, and make sure that the proxy server you are using supports the proxy UDP protocol (some proxy servers do not support, some do but it is not enabled on the server side).
