### ISSUE TITLE
关于国内抖音的脚本问题

### ISSUE THREAD

**Issue by MoSplain** [DivineEngine/Profiles#68]
https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Rewrite/Block/AdvertisingPlus.conf
这条复写内关于抖音的部分会导致进入他人主页无内容，去除后恢复正常，烦请大佬校验是否存在问题，谢谢

**Comment by ConnersHua** [comment]
我的情况不同，在 Quantumult X 中正常，在 Surge 会导致内存溢出崩溃，需要上游 [Choler](https://github.com/Choler/Surge) 更新才能解决
