### ISSUE TITLE
China.yaml 问题提交

### ISSUE THREAD

**Issue by asdfj2381k** [DivineEngine/Profiles#71]
。

**Comment by asdfj2381k** [comment]
www.nfmovies.com 经过ipip.net查询， 是美国IP。

![image](https://user-images.githubusercontent.com/56584082/102014695-42ca3600-3d92-11eb-882a-d428c4194cc0.png)

但是目前会被 `https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml` 命中
![image](https://user-images.githubusercontent.com/56584082/102014705-52497f00-3d92-11eb-87cc-0447e2a97d95.png)

**Comment by asdfj2381k** [comment]
这个网站直连访问并不是十分流畅，所以，还是推荐改一下。

**Comment by ConnersHua** [comment]
感谢反馈，已处理
