### ISSUE TITLE
apple music的icloud资料库分流

### ISSUE THREAD

**Issue by CGuoL** [DivineEngine/Profiles#72]
你好，apple music的icloud音乐资料库可用来上传自己的音乐文件，但是这功能好像是亚马逊提供的存储服务，请问下能不能加一下icloud音乐资料库同步的规则？谢谢

**Comment by ConnersHua** [comment]
已更新 Music.list，如果你是国区只想代理资料库可以只加一条规则：`DOMAIN-SUFFIX,blobstore.apple.com`

**Comment by CGuoL** [comment]
> 已更新Music.list，如果你是国区只想代理资料库可以只加一条规则：`DOMAIN-SUFFIX,blobstore.apple.com`

多谢大佬的无私奉献
