### ISSUE TITLE
Prime Video 有漏网的链接

### ISSUE THREAD

**Issue by matthuo333** [DivineEngine/Profiles#75]
通过CE系统的PV插件进行播放时，在进入菜单中始终不能进入，发现是被策略走了proxy. 所以并未过滤到RULE SET 的PV策略组中。

如果要进一步获得对应链接，是只有抓包？

**Comment by matthuo333** [comment]
发现这个 images-fe.ssl-images-amazon.com:443   走了Proxy

**Comment by ConnersHua** [comment]
CE 系统是什么
