### ISSUE TITLE
Xbox主机商店图片无法加载

### ISSUE THREAD

**Issue by tanglueyi** [DivineEngine/Profiles#83]
store-images.s-microsoft.com位于china.list
![image](https://user-images.githubusercontent.com/3315564/104121394-e0f0f200-5378-11eb-81fa-e50a1138f2ee.jpeg)
![image](https://user-images.githubusercontent.com/3315564/104121416-0847bf00-5379-11eb-9d58-50ce44211bc6.jpeg)

**Comment by ConnersHua** [comment]
感谢反馈，已处理。
