### ISSUE TITLE
DOMAIN-SUFFIX,aiseet.atianqi.com全域名屏蔽导致腾讯TV app 崩溃

### ISSUE THREAD

**Issue by babylife** [DivineEngine/Profiles#84]
目前如果启用 geosite:category-ads-all 广告域名屏蔽，里面的 xiaomitv-ads 规则会屏蔽了整个 atianqi.com 域名。但是极光TV（腾讯视频TV电视版）必需读取特定 atianqi.com 子域名（例如 tv.aiseet.atianqi.com 和 *.play.aiseet.atianqi.com）才能使用，也并非整个 atianqi.com 域名都是广告。

**Comment by ConnersHua** [comment]
感谢反馈，已处理。
