### ISSUE TITLE
请问针对Apple TV使用美区账号，Apple的相关list应该怎样搭配组合使用？

### ISSUE THREAD

**Issue by tanglueyi** [DivineEngine/Profiles#87]
看到一篇[博客文章](https://blog.royli.dev/2019/better-proxy-rules-for-apple-services)特此来提问有没有必要按照文中的方法来配置，以及您的list是否有对这种中美区账号混用场景做过优化？

**Comment by tanglueyi** [comment]
看到一篇[博客文章](https://blog.royli.dev/2019/better-proxy-rules-for-apple-services)特此来提问有没有必要按照文中的方法来配置，以及您的list是否有对这种中美区账号混用场景做过优化？

**Comment by ConnersHua** [comment]
原则上来说我提倡能直连的不代理（除非慢到无法忍受），所以这个项目的中有关 Apple 的部分，在默认配置（基本上）只有 Apple 主动或被动阻止的才有代理规则，这点在 Apple 目录的 README.md 有说明，里面的细分 list 更多是出于一时兴起的收集。

但中国大陆的网络情况复杂，不同地区、不同运营商网络表现都很难说有一个统一的方案，如就个人所在地区使用体验  App Store 的下载使用直连，Apple 的 CDN 速度很快而且挺稳定，但也有朋友只能挂代理才能获得满意的速度。

所以这个我没法做一个统一方案，只能说在「能直连的不代理」的基础上对觉得使用体验不佳的服务进行代理，如 iCloud 或 TV，或者是使用 geekdada 那样针对 CDN 或 API 进行代理。

最后对于引用，默认情况下放置在 Global.list 文件之前就能生效，有些人还用了 Apple.list 就要放在该文件之前。

而对于有些代理软件有「规则类型优先级」功能的，需要注意优先级。

**Comment by tanglueyi** [comment]
感谢您的解答，我目前是放在global和china之间来使用的，正确吗？

**Comment by ConnersHua** [comment]
正确，因为当 Apple.list 使用 DIRECT 策略时要确保 Global.list 中的代理规则生效

**Comment by tanglueyi** [comment]
> 正确，因为当 Apple.list 使用 DIRECT 策略时要确保 Global.list 中的代理规则生效（Quantumult X 因为规则类型优先级不受此限制）
明白了，谢谢您
