### ISSUE TITLE
关于Netflix近期增加的代理验证机制

### ISSUE THREAD

**Issue by Scorpion4286** [DivineEngine/Profiles#88]
感谢花姐一直以来的维护~
近期在使用Netflix分流时偶发只能观看Netflix自制剧目的情况，观察连接发现，有
dualstack.apiproxy-device-prod-nlb-1-\*.elb.us-west-2.amazonaws.com
dualstack.ichnaea-web-\*.us-west-2.elb.amazonaws.com
（注：两处*号为不固定的字符串
这样两组网络请求会随着Netflix客户端启动，影响Netflix的代理检测结果，建议将上述两条增加进Netflix.list。

**Comment by ConnersHua** [comment]
感谢反馈，已处理

**Comment by betaxab** [comment]
@Scorpion4286 这两个域名在什么客户端上可以找到？我试了 ios 和 Android 最新版本并不出现。

**Comment by Scorpion4286** [comment]
> @Scorpion4286 这两个域名在什么客户端上可以找到？我试了 ios 和 Android 最新版本并不出现。

我这边在iPad上版本号显示为13.9.0(3370)5.0.1-001的请求会包含上述两条网址，
但iPhone看起来是同版本的13.9.0(3370)不会有这个请求。
大概是Netflix在做ab Test叭…

**Comment by betaxab** [comment]
喔。那就解释的通了。。我试了好半天都不出。。
