### ISSUE TITLE
请教下Clash规则

### ISSUE THREAD

**Issue by knlvz** [DivineEngine/Profiles#89]
您好，我看Clash下的Extra目录里有Apple、Game、Google、Microsoft、Telegram等规则，这些规则是已经合并到Global规则里了嘛？还需要我手动去合并或者更改配置文件的规则配置吗？

**Comment by troyliu0105** [comment]
分离的规则只是为了方便分流。

1. 如果你想让Apple、Game这些都走一个线路，那么就只需要使用 Global。
2. 如果你想 Apple 走日本，Game 走美国等，需要在 Global 规则前，单独引用 Extra 下的规则。

**Comment by knlvz** [comment]
> 分离的规则只是为了方便分流。
> 
> 1. 如果你想让Apple、Game这些都走一个线路，那么就只需要使用 Global。
> 2. 如果你想 Apple 走日本，Game 走美国等，需要在 Global 规则前，单独引用 Extra 下的规则。

明白了，谢谢
