### ISSUE TITLE
vvebo   刷新新微博的时候会断wifi

### ISSUE THREAD

**Issue by trulynb** [DivineEngine/Profiles#9]

**Comment by trulynb** [comment]
https://apps.apple.com/cn/app/vvebo-%E5%BE%AE%E5%8D%9A%E5%AE%A2%E6%88%B7%E7%AB%AF/id670910957

**Comment by ConnersHua** [comment]
解决方法：
> 如果你在使用 quantumultx loon surge 等工具，并且出现了VVebo时间流刷新困难，同时VPN高频断开的现象。
那么你需要通过以下几个方案来解决：
如果你用的是quanx，并且引用了其他人制作的复写文件，那么你需要用解析器，过滤掉这一条复写，关键词 wb_ad。

参考来源：https://t.me/vvebochannel/10

**Comment by trulynb** [comment]
> 解决方法：
> 
> > 如果你在使用 quantumultx loon surge 等工具，并且出现了VVebo时间流刷新困难，同时VPN高频断开的现象。
> > 那么你需要通过以下几个方案来解决：
> > 如果你用的是quanx，并且引用了其他人制作的复写文件，那么你需要用解析器，过滤掉这一条复写，关键词 wb_ad。
> > 如果你不知道上述方式如何操作，这里有个更简单粗暴的方法，在主机名中添加 -*.weibo.com 。
> 
> 参考来源：https://t.me/vvebochannel/10

唉  不知道该怎么过滤   只好把https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Rewrite/Advertising.conf设置成false了
