### ISSUE TITLE
关于「动画疯」脚本/模组

### ISSUE THREAD

**Issue by sanziliu** [DivineEngine/Profiles#91]
好像去广告js都删除了，请问以后有可能再添加吗？或者因为法律或其他因素不能提供了。

多谢。

**Comment by ConnersHua** [comment]
没有提供过「动画疯」的脚本，请使用其他仓库

**Comment by sanziliu** [comment]
> 没有提供过「动画疯」的脚本，请使用其他仓库

我应该记混了，因为一直在用神机 profile，把自己编辑的也算进来了。那我再找找，多谢了。
