### ISSUE TITLE
掌上生活、京东的开屏广告拦不住神机大佬

### ISSUE THREAD

**Issue by gnod512** [DivineEngine/Profiles#94]
掌上生活、京东的开屏广告拦不住神机大佬

**Comment by ConnersHua** [comment]
京东的清除缓存还有就删掉重装，银行类的有意不做的

**Comment by gnod512** [comment]
> 京东的清除缓存还有就删掉重装，银行类的有意不做的

哦哦哦，银行类是会影响体验吗？开屏广告看着是真的讨厌....
