### ISSUE TITLE
Global列表里有规则无法被匹配

### ISSUE THREAD

**Issue by LisonChan** [DivineEngine/Profiles#96]
经过测试https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Global.list中的
DOMAIN-SUFFIX,google无法被匹配，
经过查询Surge手册后发现DOMAIN-SUFFIX应该是只能用于匹配域名如google.com等，列表里已经有了关于Google域名的DOMAIN-KEYWORD规则，所以此条应该是错误的需要修改

**Comment by ConnersHua** [comment]
<img width="1000" alt="fg" src="https://user-images.githubusercontent.com/11730838/105983306-7dcec180-60d3-11eb-9501-ae81d77f16c1.png">
<img width="1000" alt="g-a" src="https://user-images.githubusercontent.com/11730838/105983317-80311b80-60d3-11eb-902a-45e58e88c43e.png">
<img width="1000" alt="about google" src="https://user-images.githubusercontent.com/11730838/105983318-80311b80-60d3-11eb-91f6-bfac00bacd44.png">

可以匹配，如上图 `about.google`、`fonts.googleapis.com`、`www.google-analytics.com`

DOMAIN-KEYWORD,google 是对未在于列表污染中的 google 域名，如 google.com.hk 及其类似的 google.com.*、google.co.jp、google.* 以及其他更多补充

**Comment by ConnersHua** [comment]
`DOMAIN-SUFFIX,google` 是用于 google 后缀的域名如 `about.google`，`DOMAIN-KEYWORD,google` 确实是已替代该规则，后续会移除

**Comment by ConnersHua** [comment]
已处理
