### ISSUE TITLE
OriginLab 规则问题

### ISSUE THREAD

**Issue by Chandler-Lu** [DivineEngine/Profiles#99]
您好，OriginLab 官网 `DOMAIN-SUFFIX,originlab.com` 在国内大部分地区丢包严重，以至于难以访问。

由于 originlab 官网禁ping，且没有批量 tcping 的网站，下图为 www.originlab.com 所用服务器同网段 ip 的批量测试结果，
![CleanShot 2021-02-01 at 18 21 23](https://user-images.githubusercontent.com/18322610/106445706-53f21200-64ba-11eb-8062-a635cfc3c954.png)

目前 originlab 的激活规则如下：
- 正常使用时，需保证软件与 originlab 服务器的正常连接以检查授权，此时不限制 ip；
- 每半年激活一次时，需使用国内 ip 激活。

综上，权衡利弊，个人认为 originlab.com 在日常使用时应保持代理状态，激活时手动关闭即可。故该 pr 不太合适：https://github.com/DivineEngine/Profiles/pull/80

利益相关：originlab beta user
![CleanShot 2021-02-01 at 18 26 46](https://user-images.githubusercontent.com/18322610/106446369-2194e480-64bb-11eb-86dc-c393c950ff97.png)

**Comment by ConnersHua** [comment]
感谢反馈，现已将 `DOMAIN-SUFFIX,originlab.com` 移除，当需要激活时使用策略组 FInal 或 MATCH 暂时调整为 DIRECT

**Comment by Chandler-Lu** [comment]
谢谢，从抓包显示来看，所有的数据都来自 www.originlab.com <http://www.originlab.com/> ，所以大概是不用考虑分离的问题了～另外鉴于检查授权的服务器和激活用的服务器应该都是 www.originlab.com <http://www.originlab.com/>，应该也没办法分开😂
